# Service configuration
apiVersion: v1
kind: Service
metadata:
  name: order-service-local
  labels:
    app: order-service
spec:
  type: NodePort
  ports:
  - name: app-port
    port: 8080
  selector:
    app: order-service
---
# Deployment configuration
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-service-local
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-local
        image: docker.groupondev.com/venkb/order-service:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - name: app-port
          containerPort: 8080