# Service configuration
apiVersion: v1
kind: Service
metadata:
  name: payment-service-local
  labels:
    app: payment-service
spec:
  type: NodePort
  ports:
  - name: app-port
    port: 8010
  selector:
    app: payment-service
---
# Deployment configuration
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-service-local
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service-local
        image: docker.groupondev.com/venkb/payment-service
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - name: app-port
          containerPort: 8010